# Dependencies
markdown:         kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

# pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Software Dev Notes
tagline:          ''
description:      'My personal notes on software development.'
url:              http://khanhpdt.github.io

author:
  name:           'Khanh Pham'
  email:          'tungkhanh.a2@gmail.com'
  url:            https://github.com/khanhpdt

paginate:         5
paginate_path:    '/page/:num'

# Custom vars
# version:          2.0.0

github:
  repo:           https://github.com/khanhpdt/khanhpdt.github.io

gems:
  - jekyll-paginate

google_analytics_key: 'UA-75448631-1'

exclude: ['README.md', 'LICENSE']